T({
	language : {
		en : '영어',
		ko : '한국어',
		cn : '중국어'
	},
	
	menu : {
		overview : '概要',
		schedule : '日程',
		dashboard : '仪表板',
		company : '公司',
		vehicle : '车辆',
		vehicle_overview : '车辆概要',
		driver : '司机',
		reservation : '预约',
		maintenance : '维修',
		user : '用户',
		code : '代码',		
		vehicle_group : '车辆群组',
		driver_group : '司机群组',
		vehicle : '车辆',
		incident : '异常状况',
		track : '追溯',
		checkin_data : '输入数据',		
		terminal : '终端',
		consumables : '消耗品',
		consumable_code : '消耗品代码',
		health : '健康状态',
		vehicle_health : '车辆健康状态',
		consumable_health : '消耗品健康状态',
		map : '现况板',
		info : '信息',
		import_data : '数据导入',
		export_data : '数据导出',
		profile : '用户概况',
		location : '位置',
		alarm : '预警',
		vehicle_runstatus : '车辆运行状况',
		vehicle_speed_section : '车辆速度区间',
		driver_runstatus : '司机运行状况',
		driver_speed_section : '司机速度区间',
		report : '报表'
	},
	
	title : {
		map : '现况板',
		confirmation : '确认',
		information : '信息',
		vehicle_information : '车辆 信息',		
		incidents : '异常状况',
		tracking_recent_driving : '最近运行履历追溯',
		incident_details : '异常状况详细',
		position_of_incident : '异常状况地点',
		incident_list : '异常状况列表',		
		company_list : '公司列表',
		company_details : '公司详细信息',
		user_list : '用户列表',
		user_details : '用户详细列表',
		code_list : '代码列表',
		code_details : '代码详细列表',
		code_group : '代码群组',
		vehicle_group : '车辆群组',
		vehicle_group_list : '车辆群组列表',
		driver_group : '司机群组',
		driver_group_list : '司机群组列表',
		drivers_by_group : '群组司机',
		group_details : '群组 细',
		vehicles_by_group : '群组车辆',
		vehicle_list : '车辆列表',
		vehicle_details : '车辆详细',
		tracking_list : '追溯列表',
		tracking_details : '追溯详细',
		checkin_data_list : '输入信息列表',
		checkin_data_details : '输入信息详细',
		terminal_list : '终端列表',
		terminal_details : '终端详细',
		driver_list : '司机列表',
		driver_details : '司机详细',
		reservation_list : '预约列表',
		reservation_details : '预约详细',
		consumable_code_list : '消耗品代码列表',
		consumable_code_details : '消耗品代码详细',
		consumables_management : '消耗品管理',
		consumables_parts : '消耗品',
		consumable_item : '消耗品品相',
		consumable_change_history : '消耗品更换履历',
		consumable_details : '消耗品详细',
		vehicle_consumables : '车辆消耗品',
		maintenance : '维修',
		maintenance_history : '维修履历',
		vehicle_health : '车辆健康状态',
		vehicle_age : '车辆年限',
		vehicle_runtime : '车辆行驶时间',
		timing_belt_health : '同步齿带状态',
		running_distance : '行驶距离',
		engine_oil_health : '润滑油状态',
		total_running_vehicles : '总行驶车辆',
		vehicle_status : '车辆状态',
		incidents_alarm : '异常状况预警',
		add_repair : '维修内容添加',
		consumable_health : '消耗品健康状态',
		location : '位置',
		location_list : '位置列表',
		location_details : '位置详细',
		set_the_location : '位置设定',
		alarm_list : '预警列表',
		alarm_details : '预警详细',
		vehicle_runstatus : '车辆行驶状况',
		vehicle_speed_section : '车辆速度区间',
		runstatus_history : '行驶履历',
		runstatus_chart : '行驶现况表',
		driver_runstatus : '司机行驶现况',
		driver_speed_section : '司机速度区间',
		speed_section_chart : '速度区间表',
		report_list : '报表列表',
		report_details : '报表详细',
		schedule : '日程',
		vehicle_overview : '车辆概要'
	},
	
	report : {
		report : '报表',
		vehicle_health : '车辆健康状态',
		consumable_health : '消耗品健康状态',		
		vehicle_summary : '车辆行驶概况', 
		driver_summary : '司机行驶概况', 
		runtime_by_vehicles : '车辆行驶时间',
        runtime_by_drivers : '司机行驶时间',
        rundist_by_vehicles : '车辆行驶距离',
        rundist_by_drivers : '司机行驶距离',
        consumption_by_vehicles : '车辆燃料消耗量',
        consumption_by_drivers : '司机燃料消耗量',
        efficiency_by_vehicles : '车辆连比',
        efficiency_by_drivers : '司机连比',
        co2_emissions_by_vehicles : '车辆CO2排放量',
        co2_emissions_by_drivers : '司机CO2排放量',
        oprate_by_vehicles : '车辆稼动率',
        oprate_by_drivers : '司机稼动率',
        oos_cnt_by_vehicles : '车辆故障次数',
        mnt_cnt_by_vehicles : '车辆维修次数',		
		eco_index_by_vehicles : '车辆eco指数',
		eco_index_by_drivers : '司机eco指数',
		eco_drv_time_by_vehicles : '车辆经济运行时间',
		eco_drv_time_by_drivers : '司机经济运行时间',
		idle_time_by_vehicles : '车辆空转时间',
		idle_time_by_drivers : '司机별空转时间',
		ovr_spd_time_by_vehicles : '车辆超速时间',
		ovr_spd_time_by_drivers : '司机超速时间',
		sud_accel_cnt_by_vehicles : '车辆急加速时间',
		sud_accel_cnt_by_drivers : '司机急加速时间',
		sud_brake_cnt_by_vehicles : '车辆急减速时间',
		sud_brake_cnt_by_drivers : '司机急减速时间',
        mnt_time_by_vehicles : '车辆维修时间',
        mttr : '平均修理时间',
        mtbf : '平均无故障区间',		
		inc_cnt_by_drivers : '司机事故次数',
		effcc_trend : '连比趋势',
		maint_trend : '维修趋势',
		driving_trend : '行驶趋势',
		eco_driving_trend : 'Eco Driving趋势',
        co2emss_ecoindex : 'CO2排放量-Eco指数关系',
        effcc_consmpt : '连比-燃料消耗量关系',
        habit_ecoindex : '运行习惯-Eco指数关系',
        consmpt_ecoindex : '燃料消耗量-Eco指数关系',
        daily_driving_report : '日行驶报表',
        daily_driving_habit : '日运行习惯报表',
        monthly_driving : '月行驶报表',
        by_vehicles : '车辆维度',
        by_drivers : '司机维度',
        by_years : '年维度'        
	},
	
	portlet : {
		latest_incident_x : '最近异常状况履历 ({x}件)',
		upcomming_x_replacement : '更换 {x} 列表',
		today_maint_list : '维修预约车辆',
		avg_fuel_effcc : '年平均连比',
		vehicle_group_driving_summary : '车辆群组行驶信息'
	},
	
	tab : {
		info_by_vehicle : '车辆信息',
		ctrl_by_vehicle : '车辆输入信息',
		ctrl_by_driver : '司机输入信息',
		maintenance : '维修',
		grid_view : 'Grid查询',
		list_view : '列表查询'
	},
	
	button : {
		search : '검색',
		reset : '초기화',
		save : '저장',
		add : '추가',
		del : '삭제',
		cancel : '취소',
		sync : '동기화',
		file : '파일...',
		close : '닫기'
	},
	
	label : {
		summary : '总结',
		language : '语言',
		success : '成功',
		failure : '失败',
		movie : '影像',
		id : '用户名',
		name : '名称',
		desc : '说明',
		created_at : '生成日',
		updated_at : '修改日',
		date : '日期',
		image_upload : '图片上传',
		timezone : '时区',
		email : '邮件',
		sur_name : '姓',
		nick_name : '昵称',
		for_name : '名',
		enabled : '可使用',
		admin : '管理员',
		locale : '地区',
		company : '公司',
		group : '群组',
		code : '代码',
		consumable_repl : '消耗品更换',
		consumable_code : '消耗品代码',
		consumable_item : '消耗品品项',
		autofit : '自动对齐',
		refreshterm : '更新周期',
		run_dist : '行驶距离',
		run_time : '行驶时间',
		location : '位置',		
		image : '图片',
		driving : '行驶',
		reg_no : '注册号',
		manufacturer : '制造公司',	
		ownership : '所有者',
		fuel_type : '燃料类型',
		birth_year : '年限',
		status : '状态',
		remaining_fuel : '燃料余量',
		vehicle_type : '车辆类型',
		ownership_type : '所有者类型',
		total_distance : '总行驶距离',
		total_run_time : '总行驶时间',
		eco_index : 'eco指数',
		eco_run_rate : '经济行驶比率',
		official_effcc : '公认连比',
		avg_effcc : '平均连比',
		avg_consmpt : '平均燃料消耗量',
		eco_drv_time : '经济运行时间',
		ovr_spd_time : '超速时间',
		idle_time : '空转时间',
		inc_cnt : '异常状况次数',
		sud_accel_cnt : '急加速次数',
		sud_brake_cnt : '急减速次数',
		sud_cnt : '急加/减速次数',
		distance_since_new_oil : '更换润滑油后行驶距离',
		engine_oil : '引擎润滑油',
		brake_pedal : '刹车踏板',
		fuel_filter : '燃料过滤器',
		brake_oil : '刹车油',
		cooling_water : '冷却水',
		timing_belt : '同步齿带',
		spark_plug : '火花塞',		
		latitude : '纬度',
		longitude : '经度',
		latitude_min  : '最小 纬度',
		longitude_min : '最小 经度',
		latitude_max  : '最大 纬度',
		longitude_max : '最大 经度',
		driver : '司机',
		vehicle : '车辆',
		vehicle_id : '车辆ID',
		driver_id : '司机ID',
		incident : '异常状况',
		velocity : '速度',
		impulse : '冲击量',		
		impulse_threshold : '冲击量临界值',
		engine_temp : '引擎温度',
		engine_temp_threshold : '引擎温度临界值',
		obd : 'OBD',
		obd_connected : 'OBD连接',
		confirm : '确认',
		video_upload : '影像上传',
		terminal : '终端',
		datetime : '时间',
		running : '行驶中',		
		start : '开始',
		end : '结束',
		average_speed : '平均速度',
		highest_speed : '최고速度',
		fuel_consumption : '燃料消耗量',
		fuel_efficiency : '连比',
		sudden_accel : '急加速',
		sudden_brake : '急减速',		
		idling : '非行驶',
		eco_driving : '经济运行',
		over_speeding : '超速',
		co2_emissions : 'CO2排放量',
		max_cooling_water_temp : '最大冷却水温度',
		average_battery_voltage : '平均电池电压',
		division : '部门',
		title : '职务',
		social : '社会保障',
		social_id : '社会保障ID',
		serial : '序列号',
		buying : '采购',
		comment : '备注',
		reserved_date : '预约日期',
		delivery_place : '交货地点',
		destination : '目的地',
		purpose : '目的',
		item : '项目',
		acceleration : '加速率',
		recent_replacement : '最近更换',		
		last_repl_date : '最近更换日',
		miles_last_repl : '最近更换日行驶距离',
		miles_since_last_repl : '更换后行驶距离',
		next_repl_mileage : '下次更换行驶距离',
		next_repl_date : '下次更换日',
		cost : '费用',
		worker : '作业者',
		component : '组件',
		accrued_cost : '累计费用',		
		replacement : '更换',
		health_rate : '健康率',
		time : '时间',
		year : '年',
		month : '月',
		distance : '距离',
		dist : '距离',
		type : '类型',
		total : '总',
		health : '健康',
		Healthy : '良好',
		Impending : '即将更换',
		Overdue : '超过期限',	
		impending : '即将更换',
		overdue : '超过期限',	
		healthy : '良好',
		repair : '维修',
		repair_date : '维修日期',
		next_repair_date : '下次维修日次',
		repair_mileage : '维修时点行驶距离',
		repair_man : '维修工',
		repair_shop : '维修点',
		repair_time : '维修时间',
		content : '内容',		
		repl_unit : '更换单位',
		fst_repl_mileage : '最初更换行驶距离',
		fst_repl_time : '最初更换时间',		
		repl_mileage : '更换行驶距离',
		repl_time : '更换时间',
		repl_date : '更换日期',
		address : '地址',
		alarm : '预警',
		event_type : '事件类型',
		event_name : '事件',
		radius : '半径',
		location_radius : '位置半径',
		event_trigger : '事件触发',
		send_to : '发送到',
		message : '信息',
		from_date : '开始日期',
		to_date : '结束日期',
		from_time : '开始时间',
		to_time : '结束时间',
		times : '次数',
		x_from_date : '{x} 开始日',
		x_to_date : '{x} 结束日',
		x_from_time : '{x} 开始时间',
		x_to_time : '{x} 结束时间',
		phone_x : '电话号 #{x}',
		x_id : '{x} ID',
		x_no : '{x} 号',
		x_name : '{x} 名字',
		x_group : '{x} 群组',
		x_count : '{x} 次数',
		x_status : '{x} 状态',
		x_type : '{x} 类型',
		x_date : '{x} 日期',
		x_time : '{x} 时间',
		parentheses_x : ' ({x})',
		impulse_x : '{x}轴 冲击量',
		accelerate_x : '{x}轴 加速度',
		x_distance : '{x} 距离',
		x_speed : '{x} 速度',
		total_x : '总 {x}',
		lessthan_km : '{km}Km以下',
		lessthan_km_min : '{km}Km以下(分)',
		state_running : '行驶中',
		state_idle : '停车',
		state_incident : '异常状况',
		state_maint : '维修中',
		second_s : '秒',
		minute_s : '分',
		parentheses_year : '(年)',
		parentheses_month : '(月)',
		parentheses_day : '(日)',
		parentheses_hour : '(时间)',
		parentheses_min : '(份)',
		maintenance : '维修',
		period_always : '期间一直',
		period : '期间',
		chart : '表',
		driving_habit : '驾驶习惯',
		view : '查询',
		monthly_view : '月查询',
		yearly_view : '年查询',
		chart_type : '表类型',		
		line : '行',
		column : '列',
		radar : '雷达',
		speed_section : '速度区间',
		sum : '合计',
		outofservice_count : '故障次数',
		maintenance_count : '维修次数',
		maintenance_time : '维修时间',
		rate_of_oper : '稼动率',
		refresh_none : '不会自动更新',
		setting : '设定',
		dockPosition : '现况板安装位置',
		left : '左',
		right : '右',
		grade : '等级',
		eco_drv_index : '经济运行指数',
		report_code : '报表代码',
		cycle : '报告周期',
		daily : '日',
		weekly : '周',
		monthly : '月',
		yearly : '年',
		vehicle_model : '车辆型号',
		eco_level : '经济行驶级别',
		mileage_of_month : '当月行驶距离',
		consumption_of_month : '当月燃料消耗量',
		outofservice : '故障',
		today : '今天',
		yesterday : '昨天',
		ago2days : '2天前',
		ago3days : '3天前'
	},
	
	format : {
		date : 'Y-m-d',
		time : 'H:i:s',
		datetime : 'Y-m-d H:i:s'
	},
	
	msg : {
		searching : '搜索中...',
		saving : '储存中...',
		no_matching_data_found : '没有相应数据!',
		confirm_save : '确认储存?',
		confirm_delete : '确认删除?',
		confirm_do : '确认 {do}?',
		confirm_run : '确认执行?',
		processed_successfully : '正常处理完毕.',
		failed_to_save : '储存失败!',
		failed_to_delete : '删除失败!',
		failed_to_do : '{do} 失败!',
		failed_to_ajax : 'Ajax 失败!',
		invalid_form_values : '输入了无效数据',
		select_a_consumable : '选择消耗品种类',
		select_users : '需要查询预警内容的用户邮件以,来区分输入...',
		none_selected : '没有选择的项目!',
		select_x_first : '请先选择{x}',
		no_maint_history : '没有维修履历.',
		maint_on_x_next_y : '{x}维修以做 <br/> 下次维修预约日期是{y}.',
		vehicle_eco_drv_result_msg : '此车辆的ECO驾驶指数是{x}级别.<br/> 适当的管理空转时间, <span>年 {y}万元</span>以上的油耗节约.',
		driver_eco_drv_result_msg : '此司机的ECO驾驶指数是{x}级别.<br/> 适当的管理驾驶习惯, <span>年 {y}万元</span>以上的油耗节约，同事降低事故危险',
		address_notfound : '未找到({x})地址!',
		address_notfound_title : '查找失败',
		address_empty : '输入地址',
		noDriving : '没有行驶履历.',
		confirm_logout : '确认退出?'
	}
});
