T({
	language : {
		en : 'English',
		ko : 'Korean',
		cn : 'Chinese'
	},
	
	menu : {
		dashboard : 'Dashboard',
		company : 'Company',
		vehicle : 'Vehicle',
		driver : 'Driver',
		reservation : 'Reservation',
		maintenance : 'Maintenance',
		user : 'User',
		code : 'Code',		
		vehicle_group : 'Vehicle Group',
		driver_group : 'Driver Group',
		vehicle : 'Vehicle',
		incident : 'Incident',
		track : 'Track',
		checkin_data : 'CheckinData',		
		terminal : 'Terminal',
		consumables : 'Consumables',
		consumable_code : 'Consumable Code',
		health : 'Health',
		vehicle_health : 'Vehicle Health',
		consumable_health : 'Consumable Health',		
		map : 'Board',
		info : 'Info',
		incident : 'Incident',
		import_data : 'Import',
		export_data : 'Export',
		profile : 'User Profile',
		location : 'Location',
		alarm : 'Alarm',
		vehicle_runstatus : 'Vehicle RunStatus',
		driver_runstatus : 'Driver RunSatus',
		driver_speed_section : 'Drivers Speed Section'
	},
	
	title : {
		map : 'Information Board',
		confirmation : 'Confirmation',
		information : 'Information',
		vehicle_information : 'Vehicle Information',		
		incidents : 'Incidents',
		tracking_recent_driving : 'Tracking Recent Driving',
		incident_details : 'Incident Details',
		position_of_incident : 'Position of Incident',
		incident_list : 'Incident List',		
		company_list : 'Company List',
		company_details : 'Company Details',
		user_list : 'User List',
		user_details : 'User Details',
		code_list : 'Code List',
		code_details : 'Code Details',
		code_group : 'Code Group',
		vehicle_group : 'Vehicle Group',
		vehicle_group_list : 'Vehicle Group List',
		driver_group : 'Driver Group',
		driver_group_list : 'Driver Group List',
		drivers_by_group : 'Drivers By Group',
		group_details : 'Group Details',
		vehicles_by_group : 'Vehicles By Group',
		vehicle_list : 'Vehicle List',
		vehicle_details : 'Vehicle Details',
		tracking_list : 'Tracking List',
		tracking_details : 'Tracking Details',
		checkin_data_list : 'CheckinData List',
		checkin_data_details : 'CheckinData Details',
		terminal_list : 'Terminal List',
		terminal_details : 'Terminal Details',
		driver_list : 'Driver List',
		driver_details : 'Driver Details',
		reservation_list : 'Reservation List',
		reservation_details : 'Reservation Details',
		consumable_code_list : 'Consumable Code List',
		consumable_code_details : 'Consumable Code Details',
		consumables_management : 'Consumables Management',
		consumables_parts : 'Consumable Pars',
		consumable_item : 'Consumable Item',
		consumable_change_history : 'Consumable Change History',
		vehicle_consumables : 'Vehicle Consumables',
		maintenance : 'Maintenance',
		maintenance_history : 'Maintenance History',
		vehicle_health : 'Vehicle Health',
		vehicle_age : 'Vehicle Age',		
		timing_belt_health : 'Timing Belt Health',
		running_distance : 'Running Distance',
		engine_oil_health : 'Engine Oil Health',
		total_running_vehicles : 'Total Running Vehicles',
		vehicle_status : 'Vehicle Status',
		incidents_alarm : 'Incidents Alarm',
		add_repair : 'Add Repair',
		consumable_health : 'Consumable Health',
		location : 'Location',
		location_list : 'Location List',
		location_details : 'Location Details',
		set_the_location : 'Set the Location',
		alarm_list : 'Alarm List',
		alarm_details : 'Alarm Details',
		vehicle_runstatus : 'Vehicle RunStatus',
		runstatus_history : 'RunStatus History',
		runstatus_chart : 'RunStatus Chart',
		driver_runstatus : 'Driver RunStatus',
		driver_speed_section : 'Drivers Speed Section',
		speed_section_chart : 'Drivers Speed Section Chart',
		report_list : 'Report List'
	},
	
	report : {
		report : 'Report',
		vehicle_summary : 'Vehicle Running Summary',
		driver_summary : 'Driver Running Summary',
		runtime_by_vehicles : 'Runtime By Vehicles',
        runtime_by_drivers : 'Runtime By Drivers',
        rundist_by_vehicles : 'Mileage By Vehicles',
        rundist_by_drivers : 'Mileage By Drivers',
        consumption_by_vehicles : 'Consumption By Vehicles',
        consumption_by_drivers : 'Consumption By Drivers',
        efficiency_by_vehicles : 'Efficiency By Vehicles',
        efficiency_by_drivers : 'Efficiency By Drivers',
        co2_emissions_by_vehicles : 'CO2 Emissions By Vehicles',
        co2_emissions_by_drivers : 'CO2 Emissions By Drivers',
        oprate_by_vehicles : 'Rate of Operate By Vehicles',
        oprate_by_drivers : 'Rate of Operate By Drivers',
        oos_cnt_by_vehicles : 'OutOfService Count By Vehicles',
        mnt_cnt_by_vehicles : 'Maintenance Count By Vehicles',
		sud_accel_cnt_by_drivers : 'Sudden Accel Count By Drivers',
		sud_brake_cnt_by_drivers : 'Sudden Brake Count By Drivers',
		eco_drv_time_by_drivers : 'Eco-Driving Time By Drivers',
		ovr_spd_time_by_drivers : 'Over Speed Time By Drivers',
		inc_cnt_by_drivers : 'Incident Count By Drivers',
        vehicle_effcc_rel : 'Vehicle-Efficiency Rel.',
        driver_effcc_rel : 'Driver-Efficiency Rel.',
        habit_effcc_rel : 'Driver Habits-Efficiency Rel.',
        incident_effcc_rel : 'Incident-Efficiency Rel.',
        consumable_effcc_rel : 'Consumable-Efficiency Rel.',
        mnt_time_by_vehicles : 'Maintenance Time By Vehicles',
        mttr_by_vehicles : 'MTTR By Vehicles',
        mtbf_by_vehicles : 'MTBF By Vehicles',
        by_vehicles : 'By Vehicles',
        by_drivers : 'By Drivers',
        by_years : 'By Year',
	},
	
	tab : {
		info_by_vehicle : 'Information By Vehicle',
		ctrl_by_vehicle : 'Control By Vehicle',
		ctrl_by_driver : 'Control By Driver',
		maintenance : 'Maintenance',
		grid_view : 'Grid View',
		list_view : 'List View'		
	},
	
	button : {
		search : 'Search',
		reset : 'Reset',
		save : 'Save',
		add : 'Add',
		del : 'Delete',
		cancel : 'Cancel',
		sync : 'Sync',
		file : 'file...',
		close : 'Close'
	},
	
	label : {
		language : 'Language',
		success : 'Success',
		failure : 'Failure',
		id : 'ID',
		name : 'Name',
		desc : 'Desc',
		created_at : 'Created At',
		updated_at : 'Updated At',
		date : 'Date',
		image_upload : 'Image Upload',
		timezone : 'Timezone',
		email : 'E-Mail',
		sur_name : 'Sur Name',
		nick_name : 'Nick Name',
		for_name : 'For Name',
		enabled : 'Enabled',
		admin : 'Admin',
		locale : 'Locale',
		company : 'Company',
		group : 'Group',
		code : 'Code',
		consumable_repl : 'Consumable Replacement',
		consumable_code : 'Consumable Code',
		consumable_item : 'Consumable Item',
		autofit : 'Autofit',
		refreshterm : 'Refresh Every',
		run_dist : 'Run. Dist.',
		run_time : 'Run. Time.',
		location : 'Location',		
		image : 'Image',
		reg_no : 'Reg. No.',
		manufacturer : 'Manufacturer',	
		ownership : 'Ownership',
		fuel_type : 'Fuel Type',
		birth_year : 'Birth Year',
		status : 'Status',
		remaining_fuel : 'Remaining Fuel',
		distance_since_new_oil : 'Distance Since New Oil',
		engine_oil : 'Engine Oil',
		brake_pedal : 'Brake Pedal',
		fuel_filter : 'Fuel Filter',
		brake_oil : 'Brake Oil',
		cooling_water : 'Cooling Water',
		timing_belt : 'Timing Belt',
		spark_plug : 'Spark Plug',		
		lattitude : 'Lattitude',
		longitude : 'Longitude',
		lattitude_min : 'Min. Lat.',
		longitude_min : 'Min. Lng',
		lattitude_max : 'Max. Lat',
		longitude_max : 'Max. Lng',		
		driver : 'Driver',
		vehicle : 'Vehicle',
		vehicle_id : 'Vehicle Id',
		incident : 'Incident',
		velocity : 'Velocity',
		impulse : 'Impulse',		
		impulse_threshold : 'Impulse Threshold',
		engine_temp : 'Engine Temp.',
		engine_temp_threshold : 'Engine Temp Threshold',
		obd : 'OBD',
		obd_connected : 'OBD Connected',
		confirm : 'Confirm',
		video_upload : 'Video Upload',
		terminal : 'Terminal',
		datetime : 'Date/Time',
		running : 'Running',		
		start : 'Start',
		end : 'End',
		average_speed : 'Average Speed',
		highest_speed : 'Highest Speed',
		fuel_consumption : 'Fuel Consumption',
		fuel_efficiency : 'Fuel Efficiency',
		sudden_accel : 'Sudden Accel',
		sudden_brake : 'Sudden Brake',		
		idling : 'Idling',
		eco_driving : 'Eco-Driving',
		over_speeding : 'Over Speeding',
		co2_emissions : 'CO2 Emissions',
		max_cooling_water_temp : 'Max Cooling Water Temp.',
		average_battery_voltage : 'Average Battery Voltage',
		division : 'Division',
		title : 'Title',
		social : 'Social',		
		serial : 'Serial',
		buying : 'Buying',
		comment : 'Comment',
		reserved_date : 'Reserved Date',
		delivery_place : 'Delivery Place',
		destination : 'Destination',
		purpose : 'Purpose',
		item : 'Item',
		acceleration : 'Acceleration',
		recent_replacement : 'Recent Replacement',		
		last_repl_date : 'Last Repl. Date',
		miles_last_repl : 'Miles Last Repl.',
		miles_since_last_repl : 'Miles Since Last Repl.',
		next_repl_mileage : 'Next Repl. Mileage',
		next_repl_date : 'Next Repl. Date',
		cost : 'Cost',
		worker : 'Worker',
		component : 'Component',
		accrued_cost : 'Accrued Cost',		
		replacement : 'Replacement',
		health_rate : 'Health Rate',
		time : 'Time',
		year : 'Year',
		month : 'Month',
		distance : 'Distance',
		dist : 'Dist.',
		type : 'Type',
		total : 'Total',
		health : 'Health',
		Healthy : 'Healthy',
		Impending : 'Impending',
		Overdue : 'Overdue',
		healthy : 'Healthy',
		impending : 'Impending',
		overdue : 'Overdue',
		repair : 'Repair',
		repair_date : 'Repair Date',
		next_repair_date : 'Next Repair Date',
		repair_mileage : 'Repair Mileage',
		repair_man : 'Repair Man',
		repair_shop : 'Repair Shop',
		content : 'Content',		
		repl_unit : 'Replacement Unit',
		fst_repl_mileage : 'First Repl. Mileage',
		fst_repl_time : 'First Repl. Time',		
		repl_mileage : 'Repl. Mileage',
		repl_time : 'Repl. Time',
		repl_date : 'Repl. Date',
		address : 'Address',			
		alarm : 'Alarm',
		event_type : 'Event Type',
		radius : 'Radius',
		location_radius : 'Loc. Radius',
		event_trigger : 'Event Trigger',
		destination : 'Destination',
		message : 'Message',
		from_date : 'From Date',
		to_date : 'To Date',
		from_time : 'From Time',
		to_time : 'To Time',
		times : 'Times',
		x_from_date : '{x} From Date',
		x_to_date : '{x} To Date',
		x_from_time : '{x} From Time',
		x_to_time : '{x} To Time',
		phone_x : 'Phone #{x}',
		x_id : '{x} Id',
		x_no : '{x} No.',
		x_name : '{x} Name',
		x_group : '{x} Group',
		x_count : '{x} Count',
		x_status : '{x} Status',
		x_type : '{x} Type',
		x_date : '{x} Date',
		x_time : '{x} Time',
		parentheses_x : ' ({x})',
		impulse_x : 'Impulse {x}',
		accelerate_x : 'accelerate_{x}',
		x_distance : '{x} Distance',
		x_speed : '{x} Speed',
		total_x : 'Total {x}',
		lessthan_km : 'Less Than {km}Km',
		lessthan_km_min : 'Less Than {km}Km (min)',
		state_driving : 'Driving',
		state_idle : 'Idle',
		state_incident : 'Incident',
		state_maint : 'Maint.',
		second_s : 'sec.',
		minute_s : 'min.',
		maintenance : 'Maintenance',
		period_always : 'Period Always',
		period : 'Period',
		chart : 'Chart',
		driving_habit : 'Driving Habit',
		view : 'View',
		monthly_view : 'Monthly View',
		yearly_view : 'Yearly View',
		chart_type : 'Chart Type',
		line : 'Line',
		column : 'Column',
		radar : 'Radar',
		speed_section : 'Speed Section',
		sum : 'Sum',
		outofservice_count : 'OutOfService Count',
		maintenance_count : 'Maintenance Count',
		maintenance_time : 'Maintenance Time',
		rate_of_oper : 'Rate Of Oper.',
		refresh_none : 'No Refresh',
		setting : 'Setting',
		dockPosition : 'Docking Position',
		left : 'Left',
		right : 'Right'
	},
	
	format : {
		date : 'Y-m-d',
		time : 'H:i:s',
		datetime : 'Y-m-d H:i:s'
	},
	
	msg : {
		searching : 'Searching ...',
		saving : 'Saving Data...',
		no_matching_data_found : 'No matching data found!',
		confirm_save : 'Would you like to save?',
		confirm_delete : 'Would you like to delete?',
		confirm_do : 'Would you like to {do}?',
		processed_successfully : 'Have been processed successfully.',
		failed_to_save : 'Failed to save!',
		failed_to_delete : 'Failed to delete!',
		failed_to_do : 'Failed to {do}!',
		failed_to_ajax : 'Ajax communication failed!',
		invalid_form_values : 'Form fields may not be submitted with invalid values!',
		select_a_consumable : 'Select a consumable',
		select_users : 'Enter email addresses of users that you want to send an alarm, separated by , ...',
		none_selected : 'None Selected!',
		select_x_first : 'Select {x} First!',
	}
});
