T({
	language : {
		en : '영어',
		ko : '한국어',
		cn : '중국어'
	},
	
	menu : {
		overview : '개요',
		schedule : '일정',
		dashboard : '대쉬보드',
		company : '회사',
		vehicle : '차량',
		vehicle_overview : '차량 개요',
		driver : '운전자',
		reservation : '예약',
		maintenance : '정비',
		user : '사용자',
		code : '코드',		
		vehicle_group : '차량 그룹',
		driver_group : '운전자 그룹',
		vehicle : '차량',
		incident : '이상상황',
		track : '추적',
		checkin_data : '체크인정보',		
		terminal : '단말기',
		consumables : '소모비품',
		consumable_code : '소모품코드',
		health : '건강상태',
		vehicle_health : '차량 건강상태',
		consumable_health : '소모품 건강상태',
		map : '현황판',
		info : '정보',
		incident : '이상상황',
		import_data : '가져오기',
		export_data : '내보내기',
		profile : '사용자 프로파일',
		location : '위치',
		alarm : '알람',
		vehicle_runstatus : '차량별 운행현황',
		vehicle_speed_section : '차량별 속도구간',
		driver_runstatus : '운전자별 운행현황',
		driver_speed_section : '운전자별 속도구간',
		report : '리포트'
	},
	
	title : {
		map : '현황판',
		confirmation : '확인',
		information : '정보',
		vehicle_information : '차량 정보',		
		incidents : '이상상황',
		tracking_recent_driving : '최근 운행정보 추적',
		incident_details : '이상상황 상세',
		position_of_incident : '이상상황 지점',
		incident_list : '이상상황 리스트',		
		company_list : '회사 리스트',
		company_details : '회사 상세정보',
		user_list : 'User 리스트',
		user_details : 'User 상세',
		code_list : '코드 리스트',
		code_details : '코드 상세',
		code_group : '코드 그룹',
		vehicle_group : '차량 그룹',
		vehicle_group_list : '차량 그룹 리스트',
		driver_group : '운전자 그룹',
		driver_group_list : '운전자 그룹 리스트',
		drivers_by_group : '그룹별 운전자',
		group_details : '그룹 상세',
		vehicles_by_group : '그룹별 차량',
		vehicle_list : '차량 리스트',
		vehicle_details : '차량 상세',
		tracking_list : '추적 리스트',
		tracking_details : '추적 상세',
		checkin_data_list : '체크인정보 리스트',
		checkin_data_details : '체크인정보 상세',
		terminal_list : '단말기 리스트',
		terminal_details : '단말기 상세',
		driver_list : '운전자 리스트',
		driver_details : '운전자 상세',
		reservation_list : '예약 리스트',
		reservation_details : '예약 상세',
		consumable_code_list : '소모품 코드 리스트',
		consumable_code_details : '소모품 코드 상세',
		consumables_management : '소모품 관리',
		consumables_parts : '소모품목',
		consumable_item : '소모품 항목',
		consumable_change_history : '소모품 교체 이력',
		consumable_details : '소모품 상세',
		vehicle_consumables : '차량 소모품',
		maintenance : '정비',
		maintenance_history : '정비 이력',
		vehicle_health : '차량 건강상태',
		vehicle_age : '차량 연수',		
		timing_belt_health : '타이밍벨트 상태',
		running_distance : '주행거리',
		engine_oil_health : '엔진오일 상태',
		total_running_vehicles : '총 주행 차량',
		vehicle_status : '차량 상태',
		incidents_alarm : '이상상황 알림',
		add_repair : '정비내역 추가',
		consumable_health : '소모품 건강상태',
		location : '위치',
		location_list : '위치 리스트',
		location_details : '위치 상세',
		set_the_location : '위치 지정',
		alarm_list : '알람 리스트',
		alarm_details : '알람 상세',
		vehicle_runstatus : '차량별 운행현황',
		vehicle_speed_section : '차량별 속도구간',
		runstatus_history : '운행 이력',
		runstatus_chart : '운행현황 차트',
		driver_runstatus : '운전자별 주행현황',
		driver_speed_section : '운전자별 속도구간',
		speed_section_chart : '속도구간 차트',
		report_list : '리포트 리스트',
		report_details : '리포트 상세',
		schedule : '일정',
		vehicle_overview : '차량 개요'
	},
	
	report : {
		report : '리포트',
		vehicle_summary : '차량별 주행요약', 
		driver_summary : '운전자별 주행요약', 
		runtime_by_vehicles : '차량별 주행시간',
        runtime_by_drivers : '운전자별 주행시간',
        rundist_by_vehicles : '차량별 주행거리',
        rundist_by_drivers : '운전자별 주행거리',
        consumption_by_vehicles : '차량별 연료소모량',
        consumption_by_drivers : '운전자별 연료소모량',
        efficiency_by_vehicles : '차량별 연비',
        efficiency_by_drivers : '운전자별 연비',
        co2_emissions_by_vehicles : '차량별 CO2배출량',
        co2_emissions_by_drivers : '운전자별 CO2배출량',
        oprate_by_vehicles : '차량별 가동율',
        oprate_by_drivers : '운전자별 가동율',
        oos_cnt_by_vehicles : '차량별 고장횟수',
        mnt_cnt_by_vehicles : '차량별 정비횟수',
		sud_accel_cnt_by_drivers : '운전자별 급가속횟수',
		sud_brake_cnt_by_drivers : '운전자별 급감속횟수',
		eco_drv_time_by_drivers : '운전자별 경제운전시간',
		ovr_spd_time_by_drivers : '운전자별 과속시간',
		inc_cnt_by_drivers : '운전자별 사고횟수',
        vehicle_effcc_rel : '차량-연비 상관관계',
        driver_effcc_rel : '운전자-연비 상관관계',
        habit_effcc_rel : '운전자습관-연비 상관관계',
        incident_effcc_rel : '사고-연비 상관관계',
        consumable_effcc_rel : '소모품건강-연비 상관관계',
        mnt_time_by_vehicles : '차량별 정비시간',
        mttr_by_vehicles : '차량별 평균수리시간',
        mtbf_by_vehicles : '차량별 평균고장간격',
        by_vehicles : '차량 관점',
        by_drivers : '운전자별 관점',
        by_years : '년도 관점'
	},
	
	portlet : {
		latest_incident_x : '최근 이상상황 이력 ({x}건)',
		upcomming_x_replacement : '교체 {x} 리스트',
		today_maint_list : '정비 예정 차량',
		avg_fuel_effcc : '연간 평균 연비',
		vehicle_group_driving_summary : '차량 그룹별 운행 정보'
	},
	
	tab : {
		info_by_vehicle : '차량별 정보',
		ctrl_by_vehicle : '차량별 체크인정보',
		ctrl_by_driver : '운전자별 체크인정보',
		maintenance : '유지보수',
		grid_view : '그리드 보기',
		list_view : '리스트 보기'
	},
	
	button : {
		search : '검색',
		reset : '초기화',
		save : '저장',
		add : '추가',
		del : '삭제',
		cancel : '취소',
		sync : '동기화',
		file : '파일...',
		close : '닫기'
	},
	
	label : {
		language : '언어',
		success : '성공',
		failure : '실패',
		id : '아이디',
		name : '이름',
		desc : '설명',
		created_at : '생성일',
		updated_at : '수정일',
		date : '일자',
		image_upload : '사진 업로드',
		timezone : '타임존',
		email : '이메일',
		sur_name : '성',
		nick_name : '별명',
		for_name : '이름',
		enabled : '사용가능',
		admin : '관리자',
		locale : '지역',
		company : '회사',
		group : '그룹',
		code : '코드',
		consumable_repl : '소모품 교체',
		consumable_code : '소모품 코드',
		consumable_item : '소모품 항목',
		autofit : '자동맞춤',
		refreshterm : '갱신주기',
		run_dist : '주행거리',
		run_time : '주행시간',
		location : '위치',		
		image : '사진',
		reg_no : '등록번호',
		manufacturer : '제조사',	
		ownership : '소유자',
		fuel_type : '연료 타입',
		birth_year : '연식',
		status : '상태',
		remaining_fuel : '연료 잔량',
		vehicle_type : '차량 타입',
		ownership_type : '소유자 타입',
		total_distance : '총 주행거리',
		eco_index : '에코 지수',
		official_effcc : '공인 연비',
		avg_effcc : '평균 연비',
		eco_drv_time : '경제운전 시간',
		ovr_spd_time : '과속 시간',
		inc_cnt : '이상상황 횟수',
		sud_accel_cnt : '급가속 횟수',
		sud_brake_cnt : '급감속 횟수',
		distance_since_new_oil : '오일교체후 주행거리',
		engine_oil : '엔진 오일',
		brake_pedal : '브레이크 페달',
		fuel_filter : '연료필터',
		brake_oil : '브레이크 오일',
		cooling_water : '냉각수',
		timing_belt : '타이밍벨트',
		spark_plug : '점화플러그',		
		latitude : '위도',
		longitude : '경도',
		latitude_min  : '최소 위도',
		longitude_min : '최소 경도',
		latitude_max  : '최대 위도',
		longitude_max : '최대 경도',
		driver : '운전자',
		vehicle : '차량',
		vehicle_id : '차량 아이디',
		incident : '이상상황',
		velocity : '속도',
		impulse : '충격량',		
		impulse_threshold : '충격량 경계값',
		engine_temp : '엔진 온도',
		engine_temp_threshold : '엔진온도 경계값',
		obd : 'OBD',
		obd_connected : 'OBD 연결',
		confirm : '확인',
		video_upload : '비디오 업로드',
		terminal : '단말기',
		datetime : '일시',
		running : '운행중',		
		start : '시작',
		end : '완료',
		average_speed : '평균 속도',
		highest_speed : '최고 속도',
		fuel_consumption : '연료소모량',
		fuel_efficiency : '연비',
		sudden_accel : '급가속',
		sudden_brake : '급감속',		
		idling : '비운행',
		eco_driving : '경제운전',
		over_speeding : '과속',
		co2_emissions : 'CO2 배출량',
		max_cooling_water_temp : '최대 냉각수 온도',
		average_battery_voltage : '평균 배터리 전압',
		division : '부서',
		title : '직책',
		social : '사회보장',		
		serial : '일련번호',
		buying : '구매',
		comment : '코멘트',
		reserved_date : '예약 일자',
		delivery_place : '탁송장소',
		destination : '행선지',
		purpose : '목적',
		item : '항목',
		acceleration : '가속율',
		recent_replacement : '최근 교체',		
		last_repl_date : '최근 교체일',
		miles_last_repl : '최근 교체일 주행거리',
		miles_since_last_repl : '교체 후 주행거리',
		next_repl_mileage : '다음 교체 주행거리',
		next_repl_date : '다음 교체일',
		cost : '비용',
		worker : '작업자',
		component : '컴포넌트',
		accrued_cost : '누적비용',		
		replacement : '교체',
		health_rate : '건강율',
		time : '시간',
		year : '년',
		month : '월',
		distance : '거리',
		dist : '거리',
		type : '타입',
		total : '총',
		health : '건강',
		Healthy : '양호',
		Impending : '교체 임박',
		Overdue : '기한 초과',	
		impending : '교체 임박',
		overdue : '기한 초과',	
		healthy : '양호',
		repair : '정비',
		repair_date : '정비일자',
		next_repair_date : '다음 정비일자',
		repair_mileage : '정비시점 주행거리',
		repair_man : '정비공',
		repair_shop : '정비점',
		repair_time : '정비시간',
		content : '내용',		
		repl_unit : '교체 단위',
		fst_repl_mileage : '최초 교체 주행거리',
		fst_repl_time : '최초 교체 시간',		
		repl_mileage : '교체 주행거리',
		repl_time : '교체 시간',
		repl_date : '교체 일자',
		address : '주소',
		alarm : '알람',
		event_type : '이벤트 타입',
		event_name : '이벤트',
		radius : '반경',
		location_radius : '위치 반경',
		event_trigger : '이벤트 트리거',
		send_to : '보내기 대상',
		message : '메세지',
		from_date : '시작일',
		to_date : '종료일',
		from_time : '시작시간',
		to_time : '종료시간',
		times : '횟수',
		x_from_date : '{x} 시작일',
		x_to_date : '{x} 종료일',
		x_from_time : '{x} 시작시간',
		x_to_time : '{x} 종료시간',
		phone_x : '전화번호 #{x}',
		x_id : '{x} 아이디',
		x_no : '{x} 번호',
		x_name : '{x} 이름',
		x_group : '{x} 그룹',
		x_count : '{x} 횟수',
		x_status : '{x} 상태',
		x_type : '{x} 타입',
		x_date : '{x} 일자',
		x_time : '{x} 시간',
		parentheses_x : ' ({x})',
		impulse_x : '{x}축 충격량',
		accelerate_x : '{x}축 가속도',
		x_distance : '{x} 거리',
		x_speed : '{x} 속도',
		total_x : '총 {x}',
		lessthan_km : '{km}Km 이하',
		lessthan_km_min : '{km}Km 이하 (분)',
		state_driving : '운행중',
		state_idle : '정차',
		state_incident : '이상상황',
		state_maint : '정비중',
		second_s : '초',
		minute_s : '분',
		parentheses_month : '(개월)',
		parentheses_hour : '(시간)',
		parentheses_min : '(분)',
		maintenance : '정비',
		period_always : '기간 항상',
		period : '기간',
		chart : '차트',
		driving_habit : '운전습관',
		view : '보기',
		monthly_view : '월별 보기',
		yearly_view : '년별 보기',
		chart_type : '차트 타입',		
		line : '라인',
		column : '컬럼',
		radar : '레이더',
		speed_section : '속도 구간',
		sum : '합계',
		outofservice_count : '고장 횟수',
		maintenance_count : '정비 횟수',
		maintenance_time : '정비 시간',
		rate_of_oper : '가동율',
		refresh_none : '자동갱신 하지않음',
		setting : '설정',
		dockPosition : '현황패널 도킹 위치',
		left : '왼쪽',
		right : '오른쪽',
		grade : '등급',
		eco_drv_index : '경제운전 지수',
		report_code : '리포트 코드',
		cycle : '보고 주기',
		daily : '일별',
		weekly : '주별',
		monthly : '월별',
		yearly : '년별',
		vehicle_model : '차량 모델'
	},
	
	format : {
		date : 'Y-m-d',
		time : 'H:i:s',
		datetime : 'Y-m-d H:i:s'
	},
	
	msg : {
		searching : '검색중 ...',
		saving : '저장중...',
		no_matching_data_found : '해당되는 데이타가 없습니다!',
		confirm_save : '저장하시겠습니까?',
		confirm_delete : '삭제하시겠습니까?',
		confirm_do : '정말 {do}하시겠습니까?',
		processed_successfully : '정상적으로 처리되었습니다.',
		failed_to_save : '저장 실패했습니다!',
		failed_to_delete : '삭제 실패했습니다!',
		failed_to_do : '{do} 실패했습니다!',
		failed_to_ajax : 'Ajax 통신에 실패했습니다!',
		invalid_form_values : '폼 필드에 유효하지 않은 값이 있습니다',
		select_a_consumable : '소모품 종류를 선택하세요',
		select_users : '알람을 보내고자 하는 사용자의 이메일 주소를 ,로 구분하여 입력...',
		none_selected : '선택된 항목이 없습니다!',
		select_x_first : '{x}를 먼저 선택해주세요'
	}
});
